const {initializeTestEnvironment,assertFails}=require('@firebase/rules-unit-testing');
const {doc,getDoc,getDocs,collection,writeBatch,setDoc,updateDoc,serverTimestamp,Timestamp,increment}=require('firebase/firestore');
const fs=require('node:fs'),assert=require('node:assert/strict');
const empty=uid=>({version:1,currentUser:uid,activeClub:'',users:[{id:uid,name:uid,goal:4,color:'#c8dfe8',photo:''}],books:[],readings:[],clubs:[],activities:[]});
(async()=>{
 require('esbuild').buildSync({entryPoints:['shared.js','cloud.js'],bundle:true,platform:'node',format:'cjs',external:['firebase/*'],outdir:'test-results/shared',outExtension:{'.js':'.cjs'}});
 const {createCloudStore}=require('./test-results/shared/cloud.cjs');const {createSharedStore}=require('./test-results/shared/shared.cjs');
 const env=await initializeTestEnvironment({projectId:'demo-bookrats',firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync('firestore.rules','utf8')}});
 const stores=[];
 try{
  await env.clearFirestore();
  const dbA=env.authenticatedContext('alice').firestore(),dbB=env.authenticatedContext('bob').firestore(),dbE=env.authenticatedContext('eve').firestore(),anon=env.unauthenticatedContext().firestore();
  const store=(db,id)=>{const s=createSharedStore(db,id,createCloudStore(db,id));stores.push(s);return s;};
  const a=store(dbA,'alice'),b=store(dbB,'bob'),eve=store(dbE,'eve');
  const base=empty('alice');base.activeClub='c1';base.clubs=[{id:'c1',name:'Leitores',description:'Clube real',owner:'alice',members:['alice'],target:40,proposals:[],votes:{},meetings:[],comments:[]}];
  base.books=[{id:'b1',title:'Compartilhado',author:'Autora',pages:200,cover:''},{id:'b2',title:'Privado',author:'Autor',pages:100,cover:''}];
  base.readings=base.books.map((book,i)=>({id:'r'+(i+1),userId:'alice',bookId:book.id,page:10,status:'reading',clubs:i?[]:['c1'],logs:[{id:'log'+i,date:'2026-10-09',from:0,to:10,delta:10,note:'Nota privada'}]}));
  await a.load(()=>({state:base,migrated:false}));await b.load(()=>({state:empty('bob'),migrated:false}));await eve.load(()=>({state:empty('eve'),migrated:false}));
  const invite=await a.createInvite('c1');assert.match(invite.token,/^[a-f0-9]{64}$/);
  assert.equal((await b.previewInvite(invite.token)).name,'Leitores');
  await assertFails(getDoc(doc(dbB,'bookratsClubs/c1')));
  await assertFails(getDoc(doc(anon,'bookratsInvites',invite.token)));
  await assertFails(getDocs(collection(dbB,'bookratsInvites')));
  const forged=writeBatch(dbE);forged.set(doc(dbE,'bookratsClubs/c1/members/eve'),{userId:'eve',profile:empty('eve').users[0],joinedAt:serverTimestamp(),inviteToken:'0'.repeat(64)});forged.update(doc(dbE,'bookratsClubs/c1'),{revision:increment(1),updatedAt:serverTimestamp()});
  await assertFails(forged.commit());
  await a.read();let notifyJoin;const joinedSignal=new Promise(resolve=>notifyJoin=resolve);a.watch(notifyJoin,e=>{throw e;});
  assert.equal(await b.acceptInvite(invite.token),'c1');
  await Promise.race([joinedSignal,new Promise((_,reject)=>setTimeout(()=>reject(Error('Join notification timeout')),8000))]);await b.acceptInvite(invite.token);
  let bob=await b.read();assert.equal(bob.clubs[0].members.length,2);
  assert.equal(bob.books.some(x=>x.title==='Privado'),false);
  assert.equal(bob.readings.length,1);assert.equal(bob.readings[0].logs[0].note,undefined);
  await assertFails(getDoc(doc(dbB,'bookratsAccounts/alice/items/books_b2')));
  await assertFails(updateDoc(doc(dbB,'bookratsClubs/c1'),{name:'Hijacked',revision:increment(1),updatedAt:serverTimestamp()}));
  bob.clubs[0].comments.push({id:'comment1',userId:'bob',text:'Olá!',spoiler:false});await b.save(bob);
  let alice=await a.read();assert.equal(alice.clubs[0].comments[0].text,'Olá!');
  bob=await b.read();bob.books.push({id:'b3',title:'Livro do Bob',author:'Autor',pages:120,cover:''});bob.readings.push({id:'r3',userId:'bob',bookId:'b3',page:5,status:'reading',clubs:['c1'],logs:[]});await b.save(bob);
  alice=await a.read();assert.equal(alice.readings.find(r=>r.id==='r3').page,5);
  bob=await b.read();const digitalReading=bob.readings.find(r=>r.id==='r3');Object.assign(bob.books.find(b=>b.id==='b3'),{format:'digital',pages:100});Object.assign(digitalReading,{page:40,initialPage:0,logs:[{id:'digital-log',date:'2026-10-09',from:0,to:40,delta:40}]});bob.activities.push({id:'digital-event',userId:'bob',readingId:'r3',logId:'digital-log',clubs:['c1'],date:'2026-10-09',text:'Digital progress',likes:[]});await b.save(bob);
  alice=await a.read();assert.equal(alice.books.find(b=>b.id==='b3').format,'digital');assert.equal(alice.readings.find(r=>r.id==='r3').logs.length,1);
  bob=await b.read();Object.assign(bob.readings.find(r=>r.id==='r3'),{page:0,logs:[]});bob.activities=bob.activities.filter(a=>a.id!=='digital-event');await b.save(bob);
  alice=await a.read();assert.equal(alice.readings.find(r=>r.id==='r3').logs.length,0);assert.equal(alice.activities.some(a=>a.id==='digital-event'),false);
  const stale=store(dbB,'bob');let staleState=await stale.load(()=>{throw Error('Should not initialize');});
  bob=await b.read();bob.clubs[0].comments.push({id:'comment2',userId:'bob',text:'Outra mensagem',spoiler:false});await b.save(bob);
  staleState.clubs[0].comments.push({id:'comment3',userId:'bob',text:'Mensagem antiga',spoiler:false});await assert.rejects(()=>stale.save(staleState),e=>e.code==='bookrats/conflict');
  const renewed=await a.createInvite('c1',true);await assert.rejects(()=>eve.acceptInvite(invite.token),/inválido|expirou|revogado/);
  await env.withSecurityRulesDisabled(async ctx=>updateDoc(doc(ctx.firestore(),'bookratsInvites',renewed.token),{expiresAt:Timestamp.fromMillis(Date.now()-1000)}));
  await assert.rejects(()=>eve.acceptInvite(renewed.token),/inválido|expirou|revogado/);
  const active=await a.createInvite('c1',true);await a.read();await a.removeMember('c1','bob');
  await assertFails(getDoc(doc(dbB,'bookratsClubs/c1')));
  await assertFails(getDoc(doc(dbB,'bookratsClubs/c1/readings/r1')));
  assert.equal((await b.read()).clubs.length,0);
  await assert.rejects(()=>b.acceptInvite(active.token),/inválido|expirou|revogado/);
  const final=await a.read();assert.equal(final.clubs[0].members.length,1);assert.equal(final.readings.some(r=>r.id==='r3'),false);
  const fresh=await a.createInvite('c1',true);await eve.acceptInvite(fresh.token);await eve.read();await eve.removeMember('c1','eve');assert.equal((await eve.read()).clubs.length,0);
  console.log('PASS: shared clubs: join, duplicate acceptance, privacy, author permissions, comments/books across accounts, conflicts, renewal, expiry, removal and leave.');
 }finally{stores.forEach(s=>s.stop());await env.cleanup();}
})().catch(e=>{console.error(e);process.exitCode=1;});
